### ISSUE TITLE
Whitespace handling in output code

### ISSUE THREAD

**Issue by JulianSobott** [dsgnr/j2tester.com#1]
Currently the frontend collapses white spaces in the rendered output, because of this property:

```css
code#output {
    white-space: pre-line;
}
```

It would be necessary for most use cases, to preserve white spaces.
We want to use your project to render yaml code, which depends on correct indentation.

My suggested fix would be to apply this change:

```css
code#output {
    white-space: pre;
}
```

Let me know if this would work for your use case too.

# PoC

Input:

```yaml
test:
    label: 1
```

Output with `pre-line`:

```yaml
test:
label: 1
```

Output with `pre`:
```yaml
test:
    label: 1
```
